"""Database creation

Revision ID: f314654b85ce
Revises: 
Create Date: 2024-08-15 23:37:30.360408

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f314654b85ce"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "city_data",
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("region_code", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("city"),
        sa.UniqueConstraint("city"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("registration_date", sa.TIMESTAMP(), nullable=False),
        sa.Column("is_redactor", sa.Boolean(), nullable=False),
        sa.Column("is_moderator", sa.Boolean(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "accesstokens",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=43), nullable=False),
        sa.Column(
            "created_at",
            fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("token"),
    )
    op.create_index(
        op.f("ix_accesstokens_created_at"),
        "accesstokens",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "city_attractions",
        sa.Column("title_attractions", sa.String(), nullable=False),
        sa.Column("description_attractions", sa.String(), nullable=False),
        sa.Column("photo_attractions", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("city_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["city_name"], ["city_data.city"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("title_attractions"),
        sa.UniqueConstraint("title_attractions"),
    )
    op.create_table(
        "city_info",
        sa.Column("description_city", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("photo", sa.String(), nullable=False),
        sa.Column("city_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["city_name"], ["city_data.city"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("city_name"),
        sa.UniqueConstraint("city_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("city_info")
    op.drop_table("city_attractions")
    op.drop_index(op.f("ix_accesstokens_created_at"), table_name="accesstokens")
    op.drop_table("accesstokens")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("city_data")
    # ### end Alembic commands ###
